- task: UsePythonVersion@0
    inputs:
    versionSpec: '3.9'
    displayName: 'Use Python 3.9'

  - script: |
    curl -sSL install.python-poetry.org | python3 -
    export PATH=$PATH:$HOME/.poetry/bin
    poetry install --no-root
    displayName: 'Install dependencies'

  - script: echo "##vso[task.prependpath]$HOME/.poetry/bin"
    displayName: Add poetry to PATH

  - script: |
    poetry run flake8 src
    displayName: 'Linter'

  - script: |
    poetry add pytest-azurepipelines
    poetry run pytest src
    displayName: 'Tests'