stages:
- stage: 'Poetry_Install'
  jobs:
    - job: detect
      steps:
      - task: CmdLine@2
        inputs:
          script: |
            curl -sSL install.python-poetry.org | python3 -
            export PATH=$PATH:$HOME/.poetry/bin
            sudo find . -name "pyproject.toml" -exec poetry install --no-root '{}' ';'
            echo "##vso[task.prependpath]$HOME/.poetry/bin"
            poetry run flake8 src
            poetry add pytest-azurepipelines
            poetry run pytest src
