pool:
  vmImage: ubuntu-latest

variables:
  pythonVersion: '3.9'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(pythonVersion)'

- script: pip install poetry
  displayName: 'Install poetry'

- script: poetry install
  displayName: 'Install dependencies'

- script: poetry run ruff check
  displayName: 'Run linter'

- script: poetry run pytest -s
  displayName: 'Run tests'