[tool.poetry]
name = "penbot-extract"
version = "0.1.0"
description = "Penbot Extract"
authors = ["Abraham, Lijo <l.abraham@accenture.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
boto3 = "^1.34.76"
botocore = "^1.29.158"
psycopg2-binary = "^2.9.9"
pandas = "^2.2.1"
openpyxl = "^3.1.2"
validators = "0.22.0"
pyaml-env = "^1.2.1"
python-dotenv = "^1.0.1"
pydantic = "^2.6.4"
twisted = "^24.3.0"
cryptography = "^42.0.5"
setuptools = "69.2.0"
urllib3 = "2.2.1"
attrs = "^23.2.0"
idna = "^3.6"
numpy = "^1.26.4"
pycparser = "^2.22"
python-dateutil = "^2.9.0.post0"
typing-extensions = "^4.10.0"
zope-interface = "^6.2"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
