[tool.poetry]
name = "penbot-api"
version = "0.1.0"
description = "Penbot API"
authors = ["Abraham, Lijo <l.abraham@accenture.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "0.110.0"
gunicorn = "^20.1.0"
boto3 = "^1.26.158"
uvicorn = "^0.22.0"
botocore = "^1.29.158"
jinja2 = "3.1.3"
pip = "24.0"
psycopg2-binary = "^2.9.6"
setuptools = "69.2.0"
python-jose = "^3.3.0"
requests = "^2.31.0"
pyaml-env = "^1.2.1"
python-dotenv = "^1.0.0"
urllib3 = "2.2.1"



[build-system]
requires = ["setuptools","poetry-core"]
build-backend = "poetry.core.masonry.api"
