[tool.poetry]
name = "penbot-classify"
version = "0.1.0"
description = "Penbot classify"
authors = ["Abraham, Lijo <l.abraham@accenture.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
boto3 = "^1.26.158"
botocore = "^1.29.158"
psycopg2-binary = "^2.9.6"
pandas = "^2.0.2"
openpyxl = "^3.1.2"
validators = "0.22.0"
requests = "^2.31.0"
selenium = "4.16.0"
scikit-learn = "^1.3.0"
lightgbm = "^3.3.5"
pyaml-env = "^1.2.1"
python-dotenv = "^1.0.0"
webdriver-manager = "^3.8.6"
pydantic = "^2.0.3"
urllib3 = "2.2.1"
scipy = "1.12.0"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
